apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx          # arbitrary label on deployment
spec:
  replicas: 1
  selector:
    matchLabels:        # labels the replica selector should match
      app: nginx
  template:
    metadata:
      labels:
        app: nginx      # label for replica selector to match
        version: 1.7.9  # arbitrary label we can match on elsewhere
    spec:
      volumes:
      - name: nginx-htmldir-volume
        persistentVolumeClaim:
          claimName: pvc-nginx
      containers:
      - name: nginx
        image: nginx:1.7.9        
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-htmldir-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
  labels:
    name: pvc-nginx
    app: efk
spec:
  # If you are using dynamic provisioning, it is important to specify a storageClassName.
  storageClassName: "standard"
  #selector:
   # matchLabels:
    #  name: pv-nginx
     accessModes:
    # Though accessmode is already defined in pv definition. It is still needed here.
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

